### ISSUE TITLE
Behavior of 0;

### ISSUE THREAD

**Issue by mbillingr** [crcx/retro12#2]
Hi there,

While reading about Forth dialects I found out about Retro and became excited.
As an exercise I started to re-implement something like Rx on top of the Python virtual machine ([gist](https://gist.github.com/mbillingr/c2bdca4f618974e7e8d1449aba792b41)). This has been more successful than I'd expected in the beginning, but now I ran into a question:

The implementation of the `0;` word uses `zret` to exit a `repeat`/`again` loop. As far I understand `repeat` and `again` do not create a subroutine, so `0;` will leave the word. Any code after `again` will not be executed. However, the usage example has code after `again`:
```
:s:length dup repeat fetch-next 0; drop again swap - #1 - ;
```
I assume there is a fault in my reasoning about the behavior of `repeat`, `0;`, and `again`. Should it execute the `swap - #1 -` part, and how is this achieved?

Cheers,
Martin.

**Comment by crcx** [comment]
This is a documentation issue. The example should have been:

    :s:length dup [ repeat fetch-next 0; drop again ] call swap - #1 - ;

I've committed a correction to Rx.md.

**Comment by mbillingr** [comment]
I see. thank you.
